branches:
  only:
  - master
language: python
sudo: false
notifications:
  email: false
python:
- 2.7
before_install:
- git submodule update --init --recursive
install:
- wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/conda
- export PATH="$HOME/conda/bin:$PATH"
- conda config --set always_yes yes
- conda info -a
- conda env create
- export PATH="$HOME/conda/envs/blog/bin:$PATH"
- conda list
script:
- make html
after_success: bash deploy.sh
env:
  global:
    secure: bvkGxYuUqDfozvK6tPdsEspgM6Nv9Ni5zarFHowX4j5WsGA9z0+r1Re1BAbxmYy76UnjVEby9OK8JQ8fZ9BOktPkDP/ZfE4z1UvXyw9IGmmsuOIac4+Ar0uVYY+F3OsptgBZQkSQfgXYteKJyR/U9UaIuTyt7V3MhcIfW3efnED3cfpV2BZG1UZyfycBy5NpNB3EmXliMDEK+MVV26pFWT0ReLg2GwYDsNzvs8JRh5ShljWmwvsoZ4Z3GfNXdWvn4oGaYzX/Rkl3fiK/Can6YZA5UjmF5CYldV54U1UQiHdfxgnqtCRtNY2LcYvgxkb3o5WgQJdxAWy2Gh93yUoe6/XG+1e7dhEoo0tvLymSE/lfNdw1ekjDooALoRyHAwXT56lXD6Pwg8C43QYQaK+ovqXoAZEsPu2yFsBjmBLcLLyahwzCkEb2/DXEK5NQxPnqNa+t0FGPGSfyIket0hqdjLIxCoIRF/eePcGawsCAtvN7cgPP1V90uaahsu9s2oWctLqcrtrrTY2uFbMyof3toFN1jj/odVIB2R34paNkprgduvxtj1hXb8g5eSCClVFDYCrGddSoiemCuKccfUn41cnnDuT8WirLs7jJNrbsJQkVrF0V5U9U1arJeuyUKG356C7VvPvTRkg3wxpY2HLiXG21DtiqozpZkw1FdP2ByD0=
