name: blog
channels:
  - conda-forge
dependencies:
  - python=2.7
  - jupyter
  - nbconvert
  - urllib3
  - pip:
    - Jinja2==2.8
    - Markdown==2.6.7
    - MarkupSafe==0.23
    - pelican==3.6.3
    - Pygments==2.1.3
    - pylint
    - requests==2.11.1
    - six==1.10.0
    - typogrify==2.0.7
    - Unidecode==0.4.19
    - urllib3==1.18
